---
prometheus_mode: agent
prometheus_scrape_configs: "{{ lookup('template', 'prometheus_scrape.j2') | from_yaml }}"

node_exporter_listen_port: 9100
process_exporter_listen_port: 9256
promtail_http_listen_port: 7080   # Have to use a non default port, tcp 9080 is used by miarec

promtail_scrape_jobs: >-
      {{ common_promtail_scrape_jobs +
      recorder_promtail_scrape_jobs +
      screen_promtail_scrape_jobs +
      livemon_promtail_scrape_jobs +
      db_promtail_scrape_jobs +
      redis_promtail_scrape_jobs +
      web_promtail_scrape_jobs +
      celery_promtail_scrape_jobs +
      celerybeat_promtail_scrape_jobs
      }}

process_exporter_list: >-
      {{ common_process_exporter_names +
      recorder_process_exporter_names +
      screen_process_exporter_names +
      livemon_process_exporter_names +
      db_process_exporter_names +
      redis_process_exporter_names +
      web_process_exporter_names +
      celery_process_exporter_names +
      celerybeat_process_exporter_names
      }}

process_exporter_names: "{{ lookup('template', 'process_exporter_names.j2') }}"

common_process_exporter_names:
 - promtail
 - node_exporter
 - process_exporter

common_promtail_scrape_jobs: []

recorder_promtail_scrape_jobs: []
recorder_process_exporter_names: []

screen_promtail_scrape_jobs: []
screen_process_exporter_names: []

livemon_promtail_scrape_jobs: []
livemon_process_exporter_names: []

db_promtail_scrape_jobs: []
db_process_exporter_names: []

redis_promtail_scrape_jobs: []
redis_process_exporter_names: []

web_promtail_scrape_jobs: []
web_process_exporter_names: []

celery_promtail_scrape_jobs: []
celery_process_exporter_names: []

celerybeat_promtail_scrape_jobs: []
celerybeat_process_exporter_names: []
