---
all_process_exporter_names:
 - promtail
 - node_exporter
 - process_exporter


recorder_promtail_scrape_jobs: []
recorder_process_exporter_names:

screen_promtail_scrape_jobs: []
screen_process_exporter_names:

livemon_promtail_scrape_jobs: []
livemon_process_exporter_names:

db_promtail_scrape_jobs: []
db_process_exporter_names:

redis_promtail_scrape_jobs: []
redis_process_exporter_names:

web_promtail_scrape_jobs: []
web_process_exporter_names:

celery_promtail_scrape_jobs: []
celery_process_exporter_names:

celerybeat_promtail_scrape_jobs: []
celerybeat_process_exporter_names:

