---
# promtail Scrape jobs, define which log files should be tailed
# promtail_scrape_jobs: [
#   {'job_name':'apache_access', 'path':'/var/log/httpd/error.log', },
#   {'job_name':'apache_error', 'path':'/var/log/httpd/error.log', },
#   {'job_name':'celery', 'path':'/var/log/miarecweb/celery/beat.log', },
#   {'job_name':'celery', 'path':'/var/log/miarecweb/celery/worker*', }
# ]

# group_promtail_scrape_jobs: [
#   {'job_name':'apache_access', 'path':'/var/log/httpd/error.log', },
#   {'job_name':'apache_error', 'path':'/var/log/httpd/error.log', },
#   {'job_name':'celery', 'path':'/var/log/miarecweb/celery/beat.log', },
#   {'job_name':'celery', 'path':'/var/log/miarecweb/celery/worker*', }
# ]

# # Define which process to monitor
# process_exporter_names: |
#   {% raw %}
#     - comm:
#         - node_exporter
#         - process_exporter
#         - promtail
#         - celerybeat
#         - celeryd
#         - httpd
#         - miarec_livemon
#   {% endraw %}